export const menu = [
  {
    id: 1,
    title: 'Profile',
    url: '/profile',
    icon: `/images/shared/sidebar/user.svg`,
  },
  {
    id: 2,
    title: 'Settings',
    url: '/settings',
    icon: `/images/shared/sidebar/settings.svg`,
  },
  {
    id: 3,
    title: 'Request Help',
    url: '/',
    icon: `/images/shared/sidebar/question.svg`,
  },
  {
    id: 4,
    title: 'Themes',
    icon: `/images/shared/sidebar/theme.svg`,
    url: '',
    children: [
      {
        id: 1,
        title: 'Light Mode',
        icon: `/images/shared/sidebar/light.svg`,
        code: 'light',
      },
      {
        id: 2,
        title: 'Dark Mode',
        icon: `/images/shared/sidebar/dark.svg`,
        code: 'dark',
      },
    ],
  },
  {
    id: 5,
    title: 'Languages',
    icon: `/images/shared/sidebar/language.svg`,
    url: '',
    children: [
      {
        id: 1,
        code: 'en',
        label: 'EN',
        title: 'English',
        translation: 'English',
        icon: '/images/shared/language/en.svg',
      },
      {
        id: 2,
        code: 'es',
        label: 'ES',
        title: 'Spanish',
        translation: 'Español',
        icon: '/images/shared/language/es.svg',
      },
      {
        id: 3,
        code: 'ko',
        label: 'KO',
        title: 'Korean',
        translation: '한국어',
        icon: '/images/shared/language/ko.svg',
      },
      {
        id: 4,
        code: 'ng_hau',
        label: 'NG/HAU',
        title: 'Nigerian Hausa',
        translation: 'Hausa',
        icon: '/images/shared/language/ng.svg',
      },
      {
        id: 5,
        code: 'ng_ibo',
        label: 'NG/IBO',
        title: 'Nigerian Igbo',
        translation: 'Igbo',
        icon: '/images/shared/language/ng.svg',
      },
      {
        id: 6,
        code: 'ng_yor',
        label: 'NG/YOR',
        title: 'Nigerian Yoruba',
        translation: 'Yorùbá',
        icon: '/images/shared/language/ng.svg',
      },
    ],
  },
  {
    id: 6,
    title: 'Favourite Places',
    url: '/',
    icon: `/images/shared/sidebar/location.svg`,
  },
];
