export const menu = {
  Languages: {
    id: 1,
    title: 'Languages',
    icon: `/images/shared/sidebar/language.svg`,
    url: '',
    children: [
      {
        id: 1,
        code: 'en',
        label: 'EN/US',
        title: 'American English',
        translation: 'English',
        icon: '',
      },
      {
        id: 2,
        code: 'en-GB',
        label: 'EN/GB',
        title: 'British English',
        translation: 'English',
        icon: '',
      },
      {
        id: 3,
        code: 'es',
        label: 'ES',
        title: 'Spanish',
        translation: 'Español',
        icon: '',
      },
      {
        id: 4,
        code: 'fr',
        label: 'FR',
        title: 'French',
        translation: 'Français',
        icon: '',
      },
      {
        id: 5,
        code: 'ar',
        label: 'AR',
        title: 'Arabic',
        translation: 'العربية',
        icon: '',
      },
      {
        id: 6,
        code: 'zh-CN',
        label: 'ZH/CN',
        title: 'Simplified Chinese',
        translation: '简体中文',
        icon: '',
      },
      {
        id: 7,
        code: 'zh-TW',
        label: 'ZH/TW',
        title: 'Traditional Chinese',
        translation: '繁體中文',
        icon: '',
      },
      {
        id: 8,
        code: 'ja',
        label: 'JA',
        title: 'Japanese',
        translation: '日本語',
        icon: '',
      },
      {
        id: 9,
        code: 'ko',
        label: 'KO',
        title: 'Korean',
        translation: '한국어',
        icon: '',
      },
      {
        id: 10,
        code: 'vi',
        label: 'VI',
        title: 'Vietnamese',
        translation: 'Tiếng Việt',
        icon: '',
      },
      {
        id: 11,
        code: 'hau-NG',
        label: 'NG/HAU',
        title: 'Nigerian Hausa',
        translation: 'Hausa',
        icon: '',
      },
      {
        id: 12,
        code: 'yor-NG',
        label: 'NG/YOR',
        title: 'Nigerian Yoruba',
        translation: 'Yoruba',
        icon: '',
      },
      {
        id: 13,
        code: 'ewe-BJ',
        label: 'BJ/EWE',
        title: 'Benin Ewe',
        translation: 'Ewe',
        icon: '',
      },
      {
        id: 14,
        code: 'fon-BJ',
        label: 'BJ/FON',
        title: 'Benin Fon',
        translation: 'Fɔngbè',
        icon: '',
      }
    ],
  },
  
  about: {
    id: 2,
    title: 'About Map of Pi',
    icon: `/images/shared/sidebar/info.svg`,
    url: '',
    children: [
      {
        id: 1,
        title: 'App Version',
        icon: '',
        code: 'version',
      },
      {
        id: 2,
        title: 'Privacy Policy',
        icon: '',
        code: 'privacy-policy',
      },
      {
        id: 3,
        title: 'Terms of Service',
        icon: '',
        code: 'tos',
      },
    ],
  },
};
